let names = ["ريان","علي","سماح","زياد","ابراهيم"];
console.log(names[2]);
console.log(names.unshift("سعد"));
console.log(names);
console.log(names.push("بتال"));
console.log(names);
console.log(names.shift());
console.log(names);
console.log(names.pop());
console.log(names);